name: Build

on:
  push:
    branches: [ '**' ]
    tags: [ 'v*' ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload mod jar
        uses: actions/upload-artifact@v4
        with:
          name: morecrystals
          path: build/libs/morecrystals-*.jar
          if-no-files-found: error
          
      - name: Get JAR filename
        if: startsWith(github.ref, 'refs/tags/')
        id: get-jar
        run: |
          echo "JAR_FILE=$(find build/libs -name 'morecrystals-*.jar' -type f | head -n 1)" >> $GITHUB_OUTPUT
          echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          name: MoreCrystals ${{ steps.get-jar.outputs.VERSION }}
          files: ${{ steps.get-jar.outputs.JAR_FILE }}
          generate_release_notes: true
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}